version: '3'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - '2181'
  incimanager:
    image: 'r.cfcr.io/javicodema/incimanageri2a:incimanageri2a'
    ports:
      - '8081'
    depends_on:
      - zookeeper
  agents:
    image: 'r.cfcr.io/javicodema/agentsi2a:agentsi2a'
    ports:
      - '8080'
